version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    working_directory: ~/project/crm-plugin
    steps:
      - checkout
      - run:
          name: Create Strapi project
          command: cd ~/project && yarn create strapi-app crm-project --quickstart
      - run:
          name: Load the demo DB
          command: cd ~/project/crm-project && cp -R ~/project/crm-plugin/tests/integration/testing_db/.tmp .
      - run:
          name: Install CRM plugin
          command: mkdir -p ~/project/crm-project/plugins && mv ~/project/crm-plugin ~/project/crm-project/plugins/
      - run:
          name: Start Strapi project
          command: cd ~/project/crm-project && yarn install && yarn start
          background: true
      - run:
          shell: /bin/sh
          command: |
            wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 10 http://localhost:1337/auth/local
            :
      - run:
          name: Configure the plugin for testing
          command: cp ~/project/crm-project/plugins/crm-plugin/tests/integration/config/config.js.sample ~/project/crm-project/plugins/crm-plugin/tests/integration/config/config.js
      - run:
          name: Install required packages and run the test
          command: cd ~/project/crm-project/plugins/crm-plugin/ && yarn install && yarn test

workflows:
  build-and-test:
    jobs:
      - build-and-test
